---
- name: Enable and restart all core services
  service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  ignore_errors: True
  with_items:
    - "mysql"
    - "php7.4-fpm"
    - "nginx"
    - "redis-server"
    - "redis"
